# Generated by Django 5.1.15 on 2026-05-15 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('clients', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, help_text='Auto: FAC-YYYY-NNNN', max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('FACT', 'Factura'), ('FCAM', 'Factura Cambiaria'), ('FPEQ', 'Factura Pequeño Contribuyente'), ('NCRE', 'Nota de Crédito'), ('NDEB', 'Nota de Débito')], default='FACT', max_length=4)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CERTIFIED', 'Certificada'), ('CANCELLED', 'Anulada'), ('ERROR', 'Error')], db_index=True, default='DRAFT', max_length=15)),
                ('invoice_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fel_uuid', models.CharField(blank=True, db_index=True, default='', help_text='UUID asignado por SAT.', max_length=80)),
                ('fel_series', models.CharField(blank=True, default='', max_length=30)),
                ('fel_number', models.CharField(blank=True, default='', max_length=30)),
                ('fel_certification_date', models.DateTimeField(blank=True, null=True)),
                ('fel_xml', models.TextField(blank=True, default='', help_text='XML firmado y certificado.')),
                ('fel_provider', models.CharField(blank=True, default='', help_text='Certificador usado.', max_length=30)),
                ('fel_error_message', models.TextField(blank=True, default='')),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_fel_uuid', models.CharField(blank=True, default='', max_length=80)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('display_unit', models.CharField(max_length=20)),
                ('display_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_items',
                'ordering': ['invoice', 'created_at'],
            },
        ),
    ]
